### ISSUE TITLE
Sequence "\ " ignored

### ISSUE THREAD

**Issue by GiovanniSalmeri** [christianp/asciimath2tex#14]
I suspect that in the method `strip_space` the regex should be corrected in `/^(\s|\\(?!\\\s))*/`. As it is now, the sequence `\ ` is simply stripped, instead of being translated in `\,` (that is the thin space). The rendering in MathML seem to confirm that this is what should happen, and also MathJax does so. The examples in the tests where `\ ` is used seem on the contrary not correct. Am I right?

**Comment by christianp** [comment]
Thanks for reporting this! It's fixed now.

**Comment by GiovanniSalmeri** [comment]
Thank you!
