### ISSUE TITLE
Comparison with showdown-katex

### ISSUE THREAD

**Issue by fabiospampinato** [christianp/asciimath2tex#3]
There's another similar implementation [here](https://github.com/obedm503/showdown-katex/blob/master/src/asciimath-to-tex.js), have you tried? If so could we write a short comparison between the two?

**Comment by christianp** [comment]
From looking at the git history, it seems that showdown-katex just uses a lightly-modified copy of the old ASCIIMathTeXImg.js by Peter Jipsen. 
I've set up a branch called `compare-showdown-katex` in this repository, which adds another column to the test page showing showdown-katex's output for each input. It's missing a few operators, doesn't do stackrel properly, and seems not to do matrices.

**Comment by fabiospampinato** [comment]
Awesome, thanks!
