### ISSUE TITLE
Issue involving parentheses

### ISSUE THREAD

**Issue by fabiospampinato** [christianp/asciimath2tex#6]
I have the following AsciiMath expression:

```
P(B|A) = (P(A|B) * P(B))/(P(A))
```

Which this library converts to:

```
P \left( B \left \lvert A \right ) = \left( P \frac{A \left \lvert B \right ) \cdot P \left( B \right )}{P \left( A \right )} \right. \right.
```

Then rendering it via KaTeX I get:

<img width="310" alt="Screen Shot 2019-07-01 at 00 25 35" src="https://user-images.githubusercontent.com/1812093/60402954-0bb09680-9b97-11e9-8654-d1f30ed40287.png">

While instead I should get:

![image](https://user-images.githubusercontent.com/28266566/52896542-a0c47b80-3204-11e9-8db0-1317eb342f57.png)

I'm no TeX expert, I guess the generated TeX isn't quite right? 🤔

**Comment by GiovanniSalmeri** [comment]
@fabiospampinato I am trying to resolve this little bug. The problem apparently lies in the vertical bar, which is considered a `leftright_bracket` even when, as in this case, it is actually a binary operator. The same expression without the bars is parsed correctly. More or less connected seems the only other test which fails, that is `(a,b]={x in RR | a < x <= b}`: even if visually the result is accettable, the formula is parsed incorrectly. But the code is rather complex... @christianp, do you have any hint in the right direction?

Edit: I have published [Math](https://github.com/GiovanniSalmeri/yellow-math), an extension for the CMS Yellow. I translated for it asciimath2tex.js in PHP, it works very well!

**Comment by christianp** [comment]
@GiovanniSalmeri thanks for looking at this. It's a very tricky problem! I looked at this a year or two ago, but didn't get very far.

The reason this is a problem for my parser is that its grammar doesn't make it easy to deal with an ambiguous delimiter. I'll have another think about it now, but I don't have much hope!

**Comment by GiovanniSalmeri** [comment]
@christianp Thank you very much for investigating it! I suspect that in fact ASCIImath syntax is in this inherently ambiguous. Perhaps the easy way for avoiding this problem would be to modify the ASCIImath syntax and introduce different tokens for the vertical bars as delimiters (for example `:|` and `|:`), or disallowing them altogether (in the end, they can be written with `abs()`). Perhaps it would be a better compromise. Just thinking aloud!

**Comment by christianp** [comment]
I've had a closer look at the output of the standard asciimath parser, and I think it doesn't correctly identify when `|` is used as a left or right delimiter for a bracketed expression, when the other delimiter is a different symbol.
For example, `(x|` produces
```
<mrow><mo>(</mo><mi>x</mi><mrow><mo>∣</mo></mrow></mrow>
```
while `(x)` produces
```
<mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow>
```
and `|x|` produces
```
<mrow><mo>|</mo><mi>x</mi><mo>|</mo></mrow>
```
but MathJax correctly makes the delimiters stretchy in all cases, so it must be doing something to the MathML that asciimath produces.

I'm trying to work out how to replicate that in one go, in this parser!

**Comment by pkra** [comment]
>  MathJax correctly makes the delimiters stretchy in all cases, so it must be doing something to the MathML that asciimath produces.

As opposed to TeX, in MathML everything defaults to stretchy.

**Comment by christianp** [comment]
Thanks, @pkra! So it stretches based on what is in the same `<mrow>`?

**Comment by pkra** [comment]
> So it stretches based on what is in the same <mrow>?

Yes (the relevant row may be implicit).
