### ISSUE TITLE
\twoheadrightarrowtail support

### ISSUE THREAD

**Issue by GarkGarcia** [christianp/asciimath2tex#8]
Hi all. I'm working on implement LaTeX output support support for [asciidoctor/asciimath](https://github.com/asciidoctor/asciimath/pull/17), which is quite similar to what you guys are doing in here.

As stated in [here](https://github.com/asciidoctor/asciimath/pull/17), KaTeX does not support the `\twoheadrightarrowtail` macro (neither do vanilla LaTeX, `amsmath` or `amssymb`). In fact, I was surprised that I couldn't find a TeX package that supports this specific symbol.

Did you guys have any luck with this? I believe we should exchange information about this issue.

**Comment by christianp** [comment]
KaTeX doesn't have it, but MathJax does.

**Comment by christianp** [comment]
Now I've looked at what you're doing, I see that you want to know which TeX package provides this symbol: it's [`stix`](https://ctan.org/pkg/stix), according to [the comprehensive LaTeX symbols guide](http://mirror.ox.ac.uk/sites/ctan.org/info/symbols/comprehensive/symbols-a4.pdf).

**Comment by GarkGarcia** [comment]
Alright, thanks!
